import { test } from "node:test";
import assert from "node:assert/strict";
import { validateSubmission, MIN_GAME_SECS, MAX_TOKEN_SECS } from "./validate.mjs";
import { genName, isValidName, ADJ, NOU } from "./shared.mjs";

const NOW = Date.UTC(2026, 8, 10, 12);
const token = (secsAgo = 61) => ({ iat: NOW - secsAgo * 1000, id: "abc123" });
const good = () => ({ playerName: "SwiftCorgi42", score: 12, dog: "Corgi", squirrel: "Gray Squirrel" });
const errorFor = (body, payload = token()) => validateSubmission(body, payload, NOW).error;

test("accepts a normal game", () => {
  assert.deepEqual(validateSubmission(good(), token(), NOW), { entry: good(), tokenId: "abc123" });
});

test("rejects typed-in names, including forms that were accepted before", () => {
  const typed = ["Mary", "eldoggo", "eldoggo-phone", "SwiftCorgi", "SwiftCorgi0", "SwiftCorgi100",
    "swiftcorgi42", " SwiftCorgi42", "SwiftCorgi42 ", "SwiftJerk42", "", 42, null, undefined];
  for (const playerName of typed)
    assert.equal(errorFor({ ...good(), playerName }), "Invalid name", String(playerName));
});

test("names generated by older versions stay valid", () => {
  assert.ok(isValidName("LuckyCatcher24"));
  assert.ok(isValidName("SlyPup1"));
});

test("rejects dog or squirrel text that isn't in the catalog", () => {
  assert.equal(errorFor({ ...good(), dog: "any text at all" }), "Invalid dog or squirrel");
  assert.equal(errorFor({ ...good(), squirrel: "" }), "Invalid dog or squirrel");
  assert.equal(errorFor({ ...good(), dog: undefined }), "Invalid dog or squirrel");
});

test("rejects scores that are out of range or not whole numbers", () => {
  for (const score of [-1, 151, 12.5, "12", null, NaN, Infinity])
    assert.equal(errorFor({ ...good(), score }), "Invalid score", String(score));
});

test("rejects unsigned, malformed, early, and expired tokens", () => {
  assert.equal(errorFor(good(), null), "Invalid token");
  assert.equal(errorFor(good(), { id: "abc123" }), "Invalid token");
  assert.equal(errorFor(good(), { iat: NOW - 61000 }), "Invalid token");
  assert.equal(errorFor(good(), token(MIN_GAME_SECS - 1)), "Game too short");
  assert.equal(errorFor(good(), token(MAX_TOKEN_SECS + 1)), "Token expired");
});

test("rejects bodies that aren't objects", () => {
  assert.equal(errorFor(null), "Bad request");
  assert.equal(errorFor("SwiftCorgi42"), "Bad request");
});

test("every generated name validates and fits the leaderboard row", () => {
  for (let i = 0; i < 2000; i++) assert.ok(isValidName(genName()));
  const longest = Math.max(...ADJ.map(a => a.length)) + Math.max(...NOU.map(n => n.length)) + 2;
  assert.ok(longest <= 20, `longest possible name is ${longest} chars`);
});
